theme = "bogster"

[editor]
line-number = "relative"              # 行号显示方式: relative, absolute
color-modes = true                    # 模式指示器颜色
cursorline = true                     # 高亮当前行
cursorcolumn = false                  # 高亮当前列
bufferline = "multiple"               # 缓冲区标签栏显示策略: never, always, multiple
text-width = 80                       # 最大行宽度（用于 :reflow 命令和软换行）
true-color = true                     # 强制启用TrueColor
undercurl = true                      # 强制启用undercurl
# 鼠標滾輪
mouse = true                          # 启用鼠标支持
middle-click-paste = true             # 启用鼠标中键粘贴功能
scrolloff = 0                         # 滚动时，光标距离屏幕上下边缘保留的行数
scroll-lines = 3                      # 滚轮滚动行数
# 雜項
shell = ["zsh", "-c"]                 # UNIX: sh -c WINDOWS: cmd /c
clipboard-provider = "wayland"        # MAC: pasteboard X11: x-clip & x-sel WAYLAND: wayland WIN: windows TMUX: tmux TERMUX: termux NONE: none DEFAUTE: defaute
default-yank-register = '+'
gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]
rulers = [80,120]                     # 在指定列位置显示标尺线（例如 [80, 120]），可用于检查行长
# 自动化功能
idle-timeout = 250                    # 空闲触发器的超时时间（毫秒）：例如 LSP 诊断、格式化等
continue-comments = true              # 在注释区块内按 Enter 时，自动在新行开头加入注释符号（如 //、#）
insert-final-newline = true           # 保存时若文件末尾无换行符，是否自动插入一个
trim-final-newlines = true            # 保存时自动删除最后一个有效行之后的所有空行
trim-trailing-whitespace = true       # 保存时自动删除行尾空白字符
atomic-save = true                    # 原子寫入
indent-heuristic = "hybrid"           # - "simple", "tree-sitter", "hybrid" 複製上行, 語法樹, 混合
default-line-ending = "native"        # "lf", "crlf", "cr", "ff", "nel", "native" WINDOWS: CRLF, OTHER: LF
auto-format = true                    # 格式化 需要自设对应语言的formatter
# 補全
auto-completion = true                # 自动弹出补全菜单
auto-info = true                      # 自動顯示補全項的相關信息(函數簽名)
popup-border = "all"                  # 补全样式 none popup menu all
completion-timeout = 5                # 补全响应速度，默认250，5几乎即时
completion-trigger-len = 2            # 触发自动补全所需的最小字词长度（光标下单词至少几个字符）
preview-completion-insert = false     # 选中补全项目时是否立即插入（而非仅预览）
completion-replace = false            # 补全时是否替换整个单词（true）还是仅替换光标前部分（false）
path-completion = true                # 路径补全
# 用于跳转标签（如 f/F/t/T 或 easymotion）的双字符标签字母表，前面的字母优先使用（建议使用易按键的字母）
jump-label-alphabet = "arstneiodhjluygpfwbkvmcxzq"
# 行尾诊断信息的最低严重等级 "error"、"warning", "info", "hint", "disable"
end-of-line-diagnostics = "error"
# 是否读取 .editorconfig 文件中的设置（如缩排风格、行尾符等）
editor-config = true

[editor.indent-guides]
render = true
character = "│"                       # 缩进引导线字符: ▏┆┊⸽
skip-levels = 2
[editor.cursor-shape]
insert = "bar"                        # 插入模式光标形状
normal = "block"                      # 正常模式光标形状
select = "underline"                  # 选择模式光标形状

[keys.insert]
C-u = "move_line_up"
C-e = "move_line_down"
C-n = "move_char_left"
C-i = "move_char_right"
C-o = "normal_mode"
esc = ["collapse_selection", "normal_mode"]
# tab = "insert_tab"


[keys.normal]
u = "move_visual_line_up"
e = "move_visual_line_down"
n = "move_char_left"
i = "move_char_right"
C-u = "page_cursor_half_up"
C-e = "page_cursor_half_down"
C-n = "move_prev_word_start"
C-i = "move_next_word_end"
esc = ["collapse_selection", "keep_primary_selection"]
ret = ["move_line_down", "goto_first_nonwhitespace"]
"A-u" = "copy_selection_on_prev_line"
"A-e" = "copy_selection_on_next_line"
# mode
a = { a = "append_mode", i = "insert_mode", A = "insert_at_line_end", I = "insert_at_line_start" }
V = "extend_line_below"
";" = "command_mode"
#
C-w = ":buffer-close!"
g = { n = "goto_previous_buffer", i = "goto_next_buffer"}

# goto
G = "goto_last_line"
0 = "goto_line_start"
# search
l = "search_next"
L = "search_prev"
# other
C-s = ":w"
D = "delete_selection_noyank"
P = "replace_with_yanked"
r = "undo"
R = "redo"
"A-c" = "switch_to_lowercase"
# action
c = { c = "code_action", f = ":format" }


[keys.select]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
0 = "goto_line_start"
u = "move_visual_line_up"
e = "move_visual_line_down"
n = "move_char_left"
i = "move_char_right"
G = "goto_last_line"
# mode
C-o = "normal_mode"
