# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]

keymap = [
	# 模式
	{ on = [ "<Esc>" ], run = [ "escape", "unyank" ], desc = "Exit visual mode, clear selected, or cancel search" },
	{ on = [ "<C-o>" ], run = [ "escape", "unyank" ], desc = "Exit visual mode, clear selected, or cancel search" },
	{ on = [ "v" ],       run = "visual_mode",                        desc = "Enter visual mode (selection mode)" },
  # 退出挂起
	{ on = [ "q" ],     run = "quit",               desc = "退出并切换到当前目录" },
	{ on = [ "Q" ],     run = "quit --no-cwd-file", desc = "退出不切换目录" },
	{ on = [ "<C-z>" ], run = "suspend",            desc = "挂起" },


	# 导航
	{ on = [ "u" ],        run = "arrow -1" },
	{ on = [ "e" ],        run = "arrow 1" },
	{ on = [ "n" ],        run = "leave" },
	{ on = [ "i" ],        run = "enter" },
	{ on = [ "<Up>" ],     run = "arrow -1" },
	{ on = [ "<Down>" ],   run = "arrow 1" },
	{ on = [ "<Left>" ],   run = "leave" },
	{ on = [ "<Right>" ],  run = "enter" },
	{ on = [ "<C-u>" ],    run = "arrow -6" },
	{ on = [ "<C-e>" ],    run = "arrow 6" },
	{ on = [ "<C-Up>" ],   run = "arrow -6" },
	{ on = [ "<C-Down>" ], run = "arrow 6" },
	# goto
	{ on = [ "G" ], run = "arrow bot" },
	{ on = [ "g", "g" ], run = "arrow top" },
	{ on = [ "g", "/" ], run = "cd /data/data/com.termux/files" },
  { on = [ "g", "h" ], run = "cd ~" },
  { on = [ "g", "e" ], run = "cd /data/data/com.termux/files/usr/etc" },
	{ on = [ "g", "c" ], run = "cd /sdcard/AAA/dotfile/.config" },
	{ on = [ "g", "s" ], run = "cd /sdcard/AAA/dotfile/.scripts" },
	{ on = [ "g", "d" ], run = "cd /sdcard/AAA/Downloads" },
	# 多标签
	{ on = [ "<C-t>" ], run = "tab_create", desc = "创建tab" },
	{ on = [ "<C-w>" ], run = "close",      desc = "关闭tab" },
	{ on = [ "<A-1>" ], run = "tab_switch 0" },
	{ on = [ "<A-2>" ], run = "tab_switch 1" },
	{ on = [ "<A-3>" ], run = "tab_switch 2" },
	{ on = [ "<A-4>" ], run = "tab_switch 3" },
	{ on = [ "<A-5>" ], run = "tab_switch 4" },
	{ on = [ "<A-6>" ], run = "tab_switch 5" },
	{ on = [ "<A-7>" ], run = "tab_switch 6" },
	{ on = [ "<A-8>" ], run = "tab_switch 7" },
	{ on = [ "<A-9>" ], run = "tab_switch 8" },
	# 选中
	{ on = [ "<Space>" ], run = [ "toggle", "arrow 1" ], desc = "Toggle the current selection state" },
	{ on = [ "<C-a>" ],   run = "toggle_all --state=on",            desc = "Select all files" },


	# Operation
	{ on = [ "o" ],       run = "open --interactive ",         desc = "Open the selected files interactively" },
	{ on = [ "<Enter>" ], run = "open",                        desc = "Open the selected files" },
	{ on = [ "-" ],       run = "link",                        desc = "Symlink the absolute path of files" },
	{ on = [ "_" ],       run = "link --relative",             desc = "Symlink the relative path of files" },
	{ on = [ "d" ],       run = "remove",                      desc = "放入回收站" },
	{ on = [ "D" ],       run = "remove --permanently",        desc = "永久删除" },
	{ on = [ "m", "k" ],  run = "create",                      desc = "Create a file or directory (ends with / for directories)" },
	{ on = [ "r", "n" ],  run = "rename --cursor=before_ext",  desc = "Rename a file or directory" },
	{ on = [ ";" ],       run = "shell --interactive",         desc = "打开shell窗口不阻塞" },
	{ on = [ ":" ],       run = "shell --block --interactive", desc = "打开shell窗口阻塞" },
	{ on = [ "s", "s" ],  run = "plugin fzf",                  desc = "Jump to a directory, or reveal a file using fzf" },
	# 复制路径/文件名
	{ on = [ "c", "a" ], run = "copy path",             desc = "复制绝对路径" },
	{ on = [ "c", "n" ], run = "copy filename",         desc = "复制stem.ext" },
	{ on = [ "c", "s" ], run = "copy name_without_ext", desc = "复制stem" },
	{ on = [ "c", "p" ], run = "copy dirname",          desc = "复制父目录绝对路径" },
  # 复制粘贴文件
  { on = [ "y" ],         run = "yank",           desc = "Copy the selected files" },
	{ on = [ "x" ],         run = "yank --cut",     desc = "Cut the selected files" },
	{ on = [ "p" ],         run = "paste",          desc = "Paste the files" },
	{ on = [ "P" ],         run = "paste --follow", desc = "Paste the files (overwrite if the destination exists)" },

  # 隐藏文件
	{ on = [ "." ],    run = "hidden toggle", desc = "切换显示隐藏文件" },
	# 过滤项
	{ on = [ "f" ], run = "filter --smart", desc = "Filter the files" },
	# Linemode
	{ on = [ "m", "s" ], run = "linemode size",        desc = "size" },
	{ on = [ "m", "p" ], run = "linemode permissions", desc = "permissions" },
	{ on = [ "m", "m" ], run = "linemode mtime",       desc = "mtime" },
	{ on = [ "m", "n" ], run = "linemode none",        desc = "none" },
	# 搜索项
	{ on = [ "/" ], run = "find --smart",            desc = "Find next file" },
	{ on = [ "?" ], run = "find --previous --smart", desc = "Find previous file" },
	{ on = [ "l" ], run = "find_arrow",              desc = "Go to next found file" },
	{ on = [ "L" ], run = "find_arrow --previous",   desc = "Go to previous found file" },
	# 排序
	{ on = [ ",", "m" ], run = "sort modified --dir-first",               desc = "Sort by modified time" },
	{ on = [ ",", "M" ], run = "sort modified --reverse --dir-first",     desc = "Sort by modified time (reverse)" },
	{ on = [ ",", "c" ], run = "sort created --dir-first",                desc = "Sort by created time" },
	{ on = [ ",", "C" ], run = "sort created --reverse --dir-first",      desc = "Sort by created time (reverse)" },
	{ on = [ ",", "e" ], run = "sort extension --dir-first",         	    desc = "Sort by extension" },
	{ on = [ ",", "E" ], run = "sort extension --reverse --dir-first",    desc = "Sort by extension (reverse)" },
	{ on = [ ",", "a" ], run = "sort alphabetical --dir-first",           desc = "Sort alphabetically" },
	{ on = [ ",", "A" ], run = "sort alphabetical --reverse --dir-first", desc = "Sort alphabetically (reverse)" },
	{ on = [ ",", "n" ], run = "sort natural --dir-first",                desc = "Sort naturally" },
	{ on = [ ",", "N" ], run = "sort natural --reverse --dir-first",      desc = "Sort naturally (reverse)" },
	{ on = [ ",", "s" ], run = "sort size --dir-first",                   desc = "Sort by size" },
	{ on = [ ",", "S" ], run = "sort size --reverse --dir-first",         desc = "Sort by size (reverse)" },

	# Tasks
	{ on = [ "w" ], run = "tasks_show", desc = "Show the tasks manager" },
	# Help
	{ on = [ "h" ], run = "help", desc = "Help页" },
]

[tasks]

keymap = [
	{ on = [ "<Esc>" ], run = "close", desc = "Hide the task manager" },
	{ on = [ "<C-o>" ], run = "close", desc = "Hide the task manager" },
	{ on = [ "q" ], run = "close", desc = "Hide the task manager" },
	{ on = [ "w" ],     run = "close", desc = "Hide the task manager" },

	{ on = [ "u" ], run = "arrow -1", desc = "Move cursor up" },
	{ on = [ "e" ], run = "arrow 1",  desc = "Move cursor down" },

	{ on = [ "<Up>" ],   run = "arrow -1", desc = "Move cursor up" },
	{ on = [ "<Down>" ], run = "arrow 1",  desc = "Move cursor down" },

	{ on = [ "<Enter>" ], run = "inspect", desc = "Inspect the task" },
	{ on = [ "<C-c>" ], run = "cancel",  desc = "Cancel the task" },

	{ on = [ "~" ], run = "help", desc = "Open help" }
]

[select]
keymap = [
	{ on = [ "<Esc>" ],   run = "close",          desc = "Cancel selection" },
	{ on = [ "<C-o>" ],   run = "close",          desc = "Cancel selection" },
	{ on = [ "<Enter>" ], run = "close --submit", desc = "Submit the selection" },

	{ on = [ "u" ], run = "arrow -1", desc = "Move cursor up" },
	{ on = [ "e" ], run = "arrow 1",  desc = "Move cursor down" },
	{ on = [ "<C-u>" ], run = "arrow -6", desc = "Move cursor up 5 lines" },
	{ on = [ "<C-e>" ], run = "arrow 6",  desc = "Move cursor down 5 lines" },
	{ on = [ "<Up>" ],   run = "arrow -1", desc = "Move cursor up" },
	{ on = [ "<Down>" ], run = "arrow 1",  desc = "Move cursor down" },
	{ on = [ "<C-Up>" ],   run = "arrow -6", desc = "Move cursor up 5 lines" },
	{ on = [ "<C-Down>" ], run = "arrow 6",  desc = "Move cursor down 5 lines" },

	{ on = [ "~" ], run = "help", desc = "Open help" }
]

[input]

keymap = [
	{ on = [ "<Enter>" ], run = "close --submit", desc = "Submit the input" },
	{ on = [ "<Esc>" ],   run = "escape",         desc = "Go back the normal mode, or cancel input" },
	{ on = [ "<C-o>" ],   run = "escape",         desc = "Go back the normal mode, or cancel input" },

	# Mode
	{ on = [ "a", "a" ], run = "insert --append",                     desc = "Enter append mode" },
	{ on = [ "a", "i" ], run = "insert --insert",                     desc = "Enter append mode" },
	{ on = [ "A" ], run = [ "move 999", "insert --append" ],     desc = "Move to the EOL, and enter append mode" },
	{ on = [ "I" ], run = [ "move -999", "insert" ],             desc = "Move to the BOL, and enter insert mode" },
	{ on = [ "v" ], run = "visual",                              desc = "Enter visual mode" },
	{ on = [ "V" ], run = [ "move -999", "visual", "move 999" ], desc = "Enter visual mode and select all" },

	# Character-wise movement
	{ on = [ "n" ],       run = "move -1", desc = "Move back a character" },
	{ on = [ "i" ],       run = "move 1",  desc = "Move forward a character" },
	{ on = [ "<Left>" ],  run = "move -1", desc = "Move back a character" },
	{ on = [ "<Right>" ], run = "move 1",  desc = "Move forward a character" },

	# Word-wise movement
	{ on = [ "<C-n>" ],     run = "backward",              desc = "Move back to the start of the current or previous word" },
	{ on = [ "<C-i>" ],     run = "forward",               desc = "Move forward to the start of the next word" },

	# Line-wise movement
	{ on = [ "h" ],      run = "move -999", desc = "Move to the BOL" },
	{ on = [ "l" ],      run = "move 999",  desc = "Move to the EOL" },
	{ on = [ "<Home>" ], run = "move -999", desc = "Move to the BOL" },
	{ on = [ "<End>" ],  run = "move 999",  desc = "Move to the EOL" },

	# Delete
	{ on = [ "<Backspace>" ], run = "backspace",	        desc = "Delete the character before the cursor" },
	{ on = [ "<Delete>" ],    run = "backspace --under", desc = "Delete the character under the cursor" },

	# Kill
	{ on = [ "<C-u>" ], run = "kill bol",      desc = "Kill backwards to the BOL" },
	{ on = [ "<C-k>" ], run = "kill eol",      desc = "Kill forwards to the EOL" },
	{ on = [ "<C-w>" ], run = "kill backward", desc = "Kill backwards to the start of the current word" },
	{ on = [ "<A-d>" ], run = "kill forward",  desc = "Kill forwards to the end of the current word" },

	# Cut/Yank/Paste
	{ on = [ "d" ], run = "delete --cut",                              desc = "Cut the selected characters" },
	{ on = [ "D" ], run = [ "delete --cut", "move 999" ],              desc = "Cut until the EOL" },
	{ on = [ "c" ], run = "delete --cut --insert",                     desc = "Cut the selected characters, and enter insert mode" },
	{ on = [ "C" ], run = [ "delete --cut --insert", "move 999" ],     desc = "Cut until the EOL, and enter insert mode" },
	{ on = [ "x" ], run = [ "delete --cut", "move 1 --in-operating" ], desc = "Cut the current character" },
	{ on = [ "y" ], run = "yank",           desc = "Copy the selected characters" },
	{ on = [ "p" ], run = "paste",          desc = "Paste the copied characters after the cursor" },
	{ on = [ "P" ], run = "paste --before", desc = "Paste the copied characters before the cursor" },

	# 撤销重做
	{ on = [ "r" ],     run = "undo", desc = "Undo the last operation" },
	{ on = [ "R" ], run = "redo", desc = "Redo the last operation" },
	# 帮助
	{ on = [ "h" ], run = "help", desc = "Open help" }
]
